### ISSUE TITLE
Implement logging

### ISSUE THREAD

**Issue by smalers** [OpenCDSS/cdss-app-statemod-cs#3]
Logging needs to be implemented in the prototype to illustrate how that would be done.  As per internal discussions, use the [NLog](https://github.com/nlog/nlog/wiki/Tutorial) library.  For the prototype, logging should be initialized programmatically where the log file name is as follows:

```
xxx.rsp.sim.log
```

where `xxx.rsp` is the response file name, `sim` is the run mode (similar for other run modes), and `.log` at the end indicates a log file.  This will help ensure that the log file is available to diagnose issues for a response file and different run modes.

Calls to the NLog logger methods can be made directly for new code.  If it is convenient to call the old Java-like `Message` class methods, use the following mapping:

* Message.printDebug = Nlog debug if debug level in range 1-10 and trace if 11 or higher
* Message.printStatus = NLog info
* Message.printWarning = NLog warning

In general software like TSTool does not have fatal errors because warnings are provided to users that they can interpret and change input.  Similarly, for StateMod, most warnings should be informational so the user can change input.  A fatal error would be if the response file does not exist, in which case there is a bit of a dilemma.  In this situation, perhaps make the log file name `statemod.log`.   Trivial run options like -h and -v don't really need a log file but if it turns out that this is useful (like troubleshooting startup), then it may make sense to have a startup log file `statemod.log` and a specific log file.  TSTool does this also, based on whether a StartLog() command is used.

**Comment by jurentie** [comment]
Logging has been successfully implemented using [NLog](https://nlog-project.org/)
