### ISSUE TITLE
Add command line parse function

### ISSUE THREAD

**Issue by smalers** [OpenCDSS/cdss-app-statemod-cs#6]
The prototype command line application needs a way to specify the response file on the command line as per a typical C# application.  Examples of command line parsing in other OWF work include [TSTool/Java parseArgs](https://github.com/OpenCDSS/cdss-app-tstool-main/blob/master/src/DWR/DMI/tstool/TSToolMain.java) and [shell script](http://learn.openwaterfoundation.org/owf-learn-linux-shell/useful-scripts/useful-scripts/#parsing-command-line-options).  I don't know if C# has utility functions or you just need to write the code manually.  If the latter, see TSTool.  Command line options should include:

* `-v, --version`  - print the version
* `-h, --help` - print the usage
* `*.rsp` - specify the response file (no leading option needed).   The response file with our without `*.rsp` should be allowed.  If the `rsp` is omitted as a file extension, add it to the file before processing.

The absolute path to the response file should be determined by appending the command line value to the current working folder.  Internally, using absolute avoids ambiguity.

**Comment by jurentie** [comment]
I discovered that I have already copied code from Java to C# to handle argument parsing. It was done at the beginning of the project so I forgot having done it at all. There was a bug in the parsing code, however, and that has been fixed.
